segmentio/analytics-ruby

spec/segment/analytics/client_spec.rb
spec/segment/analytics/worker_spec.rb
spec/segment/analytics_spec.rb

@travisjeffery @calvinfo 
Even though the development dependency of this is not yet rspec 3, these changes will make the transition much easier when neeeded :)
Summary of Changes:
1. Following the [better specs](http://betterspecs.org/) guidelines, I changed the assertion text in specs to remove the word "should". This allows the specs to describe in more natural language what they expect to happen.
2. In a number of specs, I added an explicit assertion for the lack of an error. This will better communicate that an error was raised when not expected instead of simply that an error was raised. 
3. Instance variables were removed in favour of `let` assignments.
4. The `client_spec` had a group of specs named `#common` which had some short circuit logic to only assert for certain keys of the …

Update spec suite

---

.rspec
spec/segment/analytics/request_spec.rb
spec/segment/analytics/response_spec.rb

@calvinfo
This adds the missing `Request` and `Response` specs.
Summary of Changes:
0. Update `.rspec` file 
-  Previous formatting option was deprecated. It has since changed from `nested` to `documentation`
1. Add `Request` spec
-  Tests proper behaviour of successful, unsuccessful and errorful responses
-  Assert passed in options are honored
-  Assert default options are present
-  Assert `retry` and `sleep` logic works as intended
2. Add `Response` spec
-  Minimal spec to ensure contract is as expected (helpful if contract is unexpectedly changed in the future)

Add Request and Response specs

---

lib/segment/analytics.rb
lib/segment/analytics/client.rb
spec/segment/analytics/client_spec.rb

As per [the documentation](https://segment.com/docs/spec/common/) and [my question on twitter](http://twitter.com/f2prateek/status/677535905372966913), here’s a patch that makes it possible to pacify explicit message identifiers.

Add support for optional explicit `messageId`.

---

lib/segment/analytics/worker.rb
spec/segment/analytics/worker_spec.rb

A simplification of my needs is:
```ruby
success = true
on_error = Proc.new { success = false }
analytics = Segment::Analytics.new(write_key: 'secret', on_error: on_error)
analytics.flush
if success
end
```
This PR ensures that `Client#flush` does not ever return _before_ the error handler has been called, otherwise that might open up the possibility for me to delete the data even though an error occurred.

Ensure the error handler is called before Client#flush finishes.

---

.travis.yml
analytics-ruby.gemspec
spec/spec_helper.rb

This PR includes : 
- fix of this error : https://travis-ci.org/segmentio/analytics-ruby/jobs/173137566
- removed gem `wrong` as version 0.3.3 didn't have method `eventually`. However latest version `0.7.1` has this method introduced. 
- To fix this error I have created helper in spec_helper.rb which accepts Hash as parameter and check for expected value.
- To fix error with ruby 1.9.3 about `NoMethodError: undefined method 'spec' for nil:NilClass`, modified travis.yml and added to install latest bundler  https://travis-ci.org/segmentio/analytics-ruby/jobs/221370817#L182
@benjaminhoffman

removed gem wrong and created helper for  method

---

lib/segment/analytics/worker.rb
spec/segment/analytics/worker_spec.rb
spec/spec_helper.rb

This PR includes
- use of present? method in `is_requesting?` method of worker
- modify check for requesting in worker spec `returns true if there is a current batch`
@benjaminhoffman 
Note : Intention of this PR is to re run test in travis

Fix failing test in worker spec

---

lib/segment/analytics/client.rb
spec/segment/analytics/client_spec.rb

addresses https://github.com/segmentio/analytics-ruby/issues/93
jira https://segment.atlassian.net/browse/EPD-376
why isn't there a test already in place for this condition?
@dominicbarnes @hankim813 @segmentio/platform-integrations

Enforces userId anonId requirement

---

lib/segment/analytics.rb
spec/segment/analytics_spec.rb

Hi! 
This is an small change to fix a problem I found in your `Segment::Analytics` class. overriding  `respond_to_missing` instead of `respond_to?` is considered a better practice.
If you override `respond_to?`, Methods like: `method` are going to lie when the parameter is a ghost method name, it is going to raise an exception. This problem generates a problem when mocking `Segment::Analytics` methods in rspec tests, because for most people an instance of `Segment::Analytics` responds to track, so it can be mocked, but, with the actual implementation it raise and exception.
Best regards,
Daniel.

Implement respond_to_missing? instead of respond_to?

---

lib/segment/analytics/backoff_policy.rb
lib/segment/analytics/defaults.rb
lib/segment/analytics/request.rb
spec/segment/analytics/backoff_policy_spec.rb
spec/segment/analytics/request_spec.rb
spec/spec_helper.rb

This PR adds exponential backoff when requests are retried. 
I picked the default backoff parameter values from https://github.com/segmentio/analytics-go and https://github.com/segmentio/backo-go.

Add exponential backoff

---

lib/segment/analytics/defaults.rb
spec/segment/analytics/request_spec.rb

The format used in this PR is `analytics-ruby/1.2.3`, as mentioned in https://tools.ietf.org/html/rfc7231#section-5.5.3. 
I noticed that the format is inconsistent across other client libraries:
- [analytics-go](https://github.com/segmentio/analytics-go/blob/bdb0aeca8a993b292b85c9ec17b5ce0ff81848c8/analytics.go#L308) uses `analytics-go (version: 1.2.3)`
- [analytics-node](https://github.com/segmentio/analytics-node/blob/master/index.js#L231) uses `analytics-node 1.2.3`
Let me know if this looks good, and I'll send PRs for the other libraries

Add user agent header with library name/version

---

lib/segment/analytics/client.rb

When calling `enqueue()` an event is sometimes not sent out immediately. I noticed this when working on the E2E tests. The library seemed to be exhibiting an intermittent lag between sending events.
It's hard to write a test for this since the order of statements is indeterminate, but here are a few screenshots of logs I added to the existing code to demonstrate the issue: 
The first example is one where the event is sent out immediately. In the second example, the worker has exited by the time the item is queued, and hence it isn't sent out immediately. This bug doesn't have serious effects though, events are always eventually sent out by the next `enqueue`/`flush`.

Spawn worker after adding item to queue

---

lib/segment/analytics/defaults.rb
lib/segment/analytics/message.rb
lib/segment/analytics/message_batch.rb
lib/segment/analytics/worker.rb
spec/segment/analytics/message_batch_spec.rb
spec/segment/analytics/message_spec.rb

Log errors for messages that exceed the maximum size

---

.rubocop_todo.yml
lib/segment/analytics/client.rb
spec/segment/analytics/client_spec.rb

https://github.com/segmentio/analytics-ruby/pull/108, with two changes: 
- Only logs when the queue is indeed full, not when it is almost full
- The log is a warning instead of an error. The return value (true/false), and the `queued_messages` value can be used to recover from this situation.

Add logging if queue is full

---

lib/segment/analytics/request.rb
lib/segment/analytics/worker.rb

Reuse TCP connections

---

lib/segment/analytics/defaults.rb
lib/segment/analytics/message.rb
lib/segment/analytics/message_batch.rb
lib/segment/analytics/worker.rb
spec/helpers/runscope_client.rb
spec/segment/analytics/message_batch_spec.rb
spec/segment/analytics/message_spec.rb
spec/segment/analytics/worker_spec.rb

https://github.com/segmentio/analytics-ruby/issues/144
Includes changes from https://github.com/segmentio/analytics-ruby/pull/143.

Limit batch size to 500kb

---

bin/analytics

https://paper.dropbox.com/doc/Libraries-End-to-End-Testing-Harness-dnotyIVIGYR7lnO1LcZtM#:uid=457845578223014078216812&h2=Contract
Main changes are:
* writeKey is a flag instead of an env var
* method is a flag, instead of a top level command
* context, properties, traits etc are optional
Also fixed a bug with `screen` in the binary. Previously it was invoking `identify` instead of screen.

Update analytics binary to be compatible with the testing harness.

---

lib/segment/analytics.rb

```
balrog:web n$ be rspec
Bundler::GemRequireError: There was an error while trying to load the gem 'segment/analytics'.
Gem Load Error is: uninitialized constant Segment::Analytics::VERSION
Backtrace for gem load error is:
/Users/n/dev/rb/repos/web/vendor/bundle/ruby/2.4.0/gems/analytics-ruby-2.2.4/lib/segment/analytics/defaults.rb:12:in `<module:Request>'
/Users/n/dev/rb/repos/web/vendor/bundle/ruby/2.4.0/gems/analytics-ruby-2.2.4/lib/segment/analytics/defaults.rb:4:in `<module:Defaults>'
/Users/n/dev/rb/repos/web/vendor/bundle/ruby/2.4.0/gems/analytics-ruby-2.2.4/lib/segment/analytics/defaults.rb:3:in `<class:Analytics>'
/Users/n/dev/rb/repos/web/vendor/bundle/ruby/2.4.0/gems/analytics-ruby-2.2.4/lib/segment/analytics/defaults.rb:2:in `<module:Segment>' …
```

require version first as it is used in the defaults now

---

lib/segment/analytics/request.rb
lib/segment/analytics/worker.rb

Ref: https://github.com/segmentio/analytics-ruby/issues/167
This reverts commit 94179b8ae9b7686de462418b6a4f8c590d8902cf.

Revert "Reuse TCP connections"

---

analytics-ruby.gemspec

Fixes #176. 
This PR changes the `commander` gem dependency from a runtime dependency to a development dependency. 
This gem is currently only used in the bin script used by https://github.com/segmentio/library-e2e-tester. Since the tester is invoked in https://github.com/segmentio/analytics-ruby/blob/4b0fa63e81704ddcc55ebcbac2c618ab6ee9b6f0/Makefile#L12, it should have access to all development dependencies (installed via bundler).

Move commander to development_dependencies, fixes #176

---

spec/segment/analytics/client_spec.rb

This fixes a build failure on master, on JRuby 9.2.5.0. 
The first build that triggered this was https://github.com/segmentio/analytics-ruby/pull/183. The failure message was: 
```
Failure/Error: expect(traits[:date_time]).to eq('2013-01-01T00:00:00.000+00:00')
expected: "2013-01-01T00:00:00.000+00:00"
got: "2013-01-01T00:00:00.000Z"
(compared using ==)
```
This is a false positive, both the strings listed are valid iso8601. 
In this PR, I've changed the tests to use native iso8601 helpers for parsing.

Refine DateTime tests to use iso8601 helpers

---

lib/segment/analytics/request.rb
spec/segment/analytics/request_spec.rb

Fixes an issue mentioned in https://github.com/segmentio/analytics-ruby/issues/180. 
> The first part of the message ("Connection error") incorrectly led me to believe that the issue was in establishing a connection with Segment servers. This nudged my investigation towards HTTP-related issues and I eventually opened up a support ticket with Segment. We eventually realized the issue was a serialization error and were then able to correctly identify the problem and fix it. Had the error been labeled "Serialization error:" or something similar, finding the root of the bug would've taken much less time.

Don't assume that all errors are ConnectionErrors

---

spec/segment/analytics_spec.rb

This shaves a couple of seconds off tests, and makes them more reliable by not relying on `#sleep` calls.

Remove #sleep calls in tests

---

lib/segment/analytics.rb
lib/segment/analytics/client.rb
lib/segment/analytics/field_parser.rb
spec/segment/analytics_spec.rb

Fixes https://github.com/segmentio/analytics-ruby/issues/181. 
This PR refactors the handling of common fields, extracts a `FieldParser` that adheres to the Segment spec. 
This will result in the following behaviour changes: 
- `alias` will now accept `anonymous_id`
- `group` will now accept `anonymous_id`
- `page` will now validate that `name` is non-empty
As I refactored this to adhere to the [Segment spec](https://segment.com/docs/spec/screen/), I found a couple of deviations from the spec:
- `options` is accepted in every call, but not mentioned in the spec
- `screen` takes a `category` parameter, which is not mentioned in the spec
I've retained these for backwards compatibility.

Allow anonymous_id in alias

---

lib/segment/analytics/field_parser.rb
spec/segment/analytics/client_spec.rb
spec/spec_helper.rb

Fixes #192.
This bug was introduced in #188, I misread the Segment spec.

Make :name optional in #page

---

History.md

Due to a bug in the release script, we accidentally released 2.2.7
directly instead of going through a pre-release.

Update history to reflect 2.2.7 release

---

RELEASING.md

Fixes a mistake in release steps introduced in https://github.com/segmentio/analytics-ruby/pull/196/commits/343e3d186804735500269b094a880bce481f0059. We can't just re-tag the commit for a pre-release, will need to update `version.rb` as well.

Fix steps in RELEASING.md for pre-releases

---

.travis.yml

Travis doesn't support 1.9.3 anymore, as it looks for RVM binaries
and they aren't available for 14.04.
Ref: https://rvm.io/binaries/ubuntu/16.04/x86_64/

Remove 1.9.3 from test matrix

---

lib/segment/analytics/message_batch.rb
lib/segment/analytics/worker.rb
spec/segment/analytics/worker_spec.rb

Fixes the second part of https://github.com/segmentio/analytics-ruby/issues/180. First part was handled in https://github.com/segmentio/analytics-ruby/pull/187. 
> The second surprise was that not only did we lose the events with an unserializable property (the "bad events"), but we also lost an order of magnitude more unrelated "good" events. Any good event in the same Rails process as a bad event had a chance of not making it to our destinations. My unsubstantiated hunch is that if a bad event is enqueued with a .track call, then all events in the batch (good or bad) will fail to make it to Segment servers.

Isolate and report serialization errors

---

lib/segment/analytics/client.rb

Without this, some modern rubies will emit this warning:
/usr/local/bundle/gems/analytics-ruby-2.2.7/lib/segment/analytics/client.rb:31: warning: instance variable @worker_thread not initialized

Explicitly initialize @worker_thread

---

.rubocop.yml
.travis.yml
analytics-ruby.gemspec
spec/segment/analytics/client_spec.rb

Includes minor code/docs cleanup in areas that were 1.9-specific. 
Ref: [Ruby 2.0 EOL'ed 3 years ago](https://endoflife.date/ruby).

Set minimum ruby version to 2.0

---

spec/segment/analytics/client_spec.rb
spec/segment/analytics/worker_spec.rb
spec/spec_helper.rb

A few unit tests were sending actual HTTP requests to Segment. Added mocks/stubs at the right places to prevent this from happening.
Tests used to take ~20 seconds to run on my machine, they now take ~1.5 seconds.

Avoid network calls in tests

---

lib/segment/analytics/request.rb

The client logs invalid data in the stubbed mode.
Example message: `[analytics-ruby] stubbed request to /v1/import: write key = test-key, batch = JSON.generate(#<Segment::Analytics::MessageBatch:0x00007fe40420b490>)`
Expected: actual hash instead of `<Segment::Analytics::MessageBatch:0x00007fe40420b490>`.

Fix stubbed request message

---

lib/segment/analytics.rb
lib/segment/analytics/transport.rb
lib/segment/analytics/worker.rb
spec/segment/analytics/transport_spec.rb
spec/segment/analytics/worker_spec.rb

Fixes #148.
- Rename `Analytics::Request` -> `Analytics::Transport`
- This object no longer represents _one_ request, it supports sending multiple requests and a `shutdown` method. `Transport` seemed like a better name
- Rename `Transport#post` -> `Transport#send`
- A `Transport` object's interface doesn't have to be HTTP-aware, just `send` should do. 
- Add `Tranport#shutdown` to close persistent connections
- Re-use `Transport` object in `Analytics::Worker`
For a commit-wise split of changes, see [this diff](https://github.com/segmentio/analytics-ruby/compare/4675099...417c064).
There was a previous failed attempt to fix this in #149. That had to be reverted because of #167. The error happened when many `Analytics::Client` objects were created, instead of a singleton client (a valid …

Re-use TCP connections across API calls

---

.travis.yml
History.md
lib/segment/analytics/utils.rb
lib/segment/analytics/version.rb

Issue #223 Update the default originalTimestamp to send 6 decimal places to the server

Changed the fractional digits to display 6 places

---

README.md
lib/segment/analytics.rb
lib/segment/analytics/client.rb
lib/segment/analytics/test_queue.rb
spec/segment/analytics/test_queue_spec.rb
spec/segment/analytics_spec.rb

Currently, we need to manually stub and override various functions within the gem to make it possible to test in rspec. This PR adds that functionality as an option to the gem itself. Perhaps also helpful, but not included here, would be some spec helpers for analytics (which we also have developed ourselves). Appreciate any feedback!

Add test option and queue for easier testing

---

History.md
lib/segment/analytics/version.rb
lib/segment/analytics/worker.rb

This change will allow users to override the default options so the library can be more flexible

enable-overriding-transport-options Pass options when initializing Transport

---

README.md

I ran into this with version 2.4.0, not sure if this is a just a typo or if the interface changed between versions.

Fix test queue reset! documentation

---

lib/segment/analytics/client.rb
spec/segment/analytics/client_spec.rb

By using Segment in our application, we realized that the test events are also sent to the production source (therefore test persons count as MTU).
So I made a quick change to fix that and added a test to ensure that the "real" queue does not change.
Please, let me know what you think about it :)

Not enqueuing test action in real queue

---

README.md
lib/segment/analytics/version.rb

Issue: We have integrated segment events to `slack` and we are getting segment events triggered when the tests run in CI.
From the documentation I thought adding `test: true` while initializing will stub the actions also. But `test: true` will only make the responses available in `test_queue` but still actually send the request through the network.
It would be helpful to mention about stubbing in the `test` section.
Suggestion: The long term goal can be to do the stubbing by default in `test` mode. I can create a pr for that if everyone agrees.

Mentioning about stubbing actions during tests.

---

lib/analytics-ruby.rb
lib/segment.rb
lib/segment/analytics.rb
lib/segment/analytics/backoff_policy.rb
lib/segment/analytics/client.rb
lib/segment/analytics/defaults.rb
lib/segment/analytics/field_parser.rb
lib/segment/analytics/logging.rb
lib/segment/analytics/message_batch.rb
lib/segment/analytics/response.rb
lib/segment/analytics/test_queue.rb
lib/segment/analytics/transport.rb
lib/segment/analytics/utils.rb
lib/segment/analytics/version.rb
lib/segment/analytics/worker.rb
spec/isolated/json_example.rb
spec/isolated/with_active_support.rb
spec/isolated/with_active_support_and_oj.rb
spec/isolated/with_oj.rb
spec/segment/analytics/backoff_policy_spec.rb
spec/segment/analytics/client_spec.rb
spec/segment/analytics/message_batch_spec.rb
spec/segment/analytics/response_spec.rb
spec/segment/analytics/test_queue_spec.rb
spec/segment/analytics/transport_spec.rb
spec/segment/analytics/worker_spec.rb
spec/segment/analytics_spec.rb
spec/spec_helper.rb

This low effort change greatly changes the outcome of how many strings are allocated in supported Ruby versions.

Lower allocated and retained strings

---

.github/workflows/gem-push.yml
.github/workflows/ruby.yml
Gemfile
analytics-ruby.gemspec
lib/segment/analytics/message_batch.rb
spec/segment/analytics/message_batch_spec.rb
spec/spec_helper.rb

Push raising error message
